"""
Report Formatter — converts synthesis output to multiple formats.
ResearchPilot — Amazon Nova AI Hackathon 2026
"""
import json
from datetime import datetime
from typing import Optional


class ReportFormatter:
    """Formats research reports as Markdown, HTML, or JSON."""

    def to_markdown(self, report: dict) -> str:
        """Generate a full Markdown report."""
        ts = datetime.now().strftime("%B %d, %Y %H:%M")
        confidence_emoji = "🟢" if report["confidence_score"] >= 0.75 else \
                           "🟡" if report["confidence_score"] >= 0.5 else "🔴"
        human_flag = "\n> ⚠️ **Human review recommended** — confidence below threshold.\n" \
                     if report.get("needs_human_review") else ""

        sources_md = "\n".join(
            f"{i+1}. [{s['title']}]({s['url']}) *({s['type']})*"
            for i, s in enumerate(report.get("sources", []))
        )

        return f"""# ResearchPilot Report
**Query:** {report['query']}
**Generated:** {ts}
**Sources analyzed:** {report['num_sources']}
**Confidence:** {confidence_emoji} {report['confidence_score']:.0%}
{human_flag}
---

{report['report_markdown']}

---

## Sources
{sources_md}

---
*Generated by ResearchPilot — Powered by Amazon Nova*
"""

    def to_html(self, report: dict) -> str:
        """Generate an HTML report with basic styling."""
        import markdown as md
        markdown_content = self.to_markdown(report)
        body = md.markdown(markdown_content, extensions=["tables", "fenced_code"])
        return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>ResearchPilot — {report['query']}</title>
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px;
            margin: 0 auto; padding: 2rem; color: #222; }}
    h1 {{ color: #1a1a2e; border-bottom: 3px solid #0891b2; padding-bottom: 0.5rem; }}
    h2 {{ color: #0d3259; }}
    blockquote {{ background: #fff3cd; border-left: 4px solid #f59e0b;
                  padding: 0.5rem 1rem; margin: 1rem 0; }}
    code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
    a {{ color: #0891b2; }}
    .footer {{ color: #888; font-size: 0.85rem; margin-top: 2rem; }}
  </style>
</head>
<body>
{body}
<p class="footer">Generated by ResearchPilot — Powered by Amazon Nova AI</p>
</body>
</html>"""

    def to_json(self, report: dict) -> str:
        """Serialize full report to JSON."""
        return json.dumps(report, indent=2, ensure_ascii=False)

    def save(self, report: dict, base_path: str = "report") -> dict:
        """Save report in all formats. Returns dict of file paths."""
        paths = {}
        for fmt, content, ext in [
            ("markdown", self.to_markdown(report), "md"),
            ("html", self.to_html(report), "html"),
            ("json", self.to_json(report), "json"),
        ]:
            path = f"{base_path}.{ext}"
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            paths[fmt] = path
        return paths
